alias c='clear'
alias ll='ls -al'
alias d='ls -al'
alias ..='cd ..'
alias ....='cd ../..'
alias ......='cd ../../..'
alias t='cat'
alias copy='cp'
alias md='mkdir'
alias rd='rmdir'

alias home='cd ~'
alias del='rm'
alias pu='pushd'
alias po='popd'

alias g='gvim'

alias gstat='git status'
alias gadd='git add'
alias gd='git diff'
alias gds='git diff --staged'
alias gdiff='git difftool -y'
alias commit='git commit'
alias log='git log'
alias logp='git log --date=iso --pretty=format:"%H %C(yellow)%ad %C(bold cyan)%ae %C(green)%s"'
alias pull='git pull'
alias push='git push'
alias branch='git branch'
alias branches='git log --oneline --decorate --graph --all'

alias dinfo='docker info'
alias dps='docker ps'
alias drun='docker run'
alias dstop='docker stop'
alias drm='docker rm'
alias drmi='docker rmi'
alias di='docker images'
alias dpush='docker push'
alias dpull='docker pull'
alias dlog='docker logs'


alias hana='pushd ~/hanarp'
alias src='pushd ~/hanarp/src'
alias core='pushd ~/hanarp/src/core'
alias cmd='pushd ~/hanarp/src/cmd'
alias bin='pushd ~/hanarp/bin'

