alias c='clear'
alias ll='ls -al'
alias d='ls -al'
alias ..='cd ..'
alias ....='cd ../..'
alias ......='cd ../../..'
alias t='cat'
alias copy='cp'

alias home='cd ~'

alias g='gvim'

alias gstat='git status'
alias gadd='git add'
alias gd='git diff'
alias gds='git diff --staged'
alias gdiff='git difftool -y'
alias commit='git commit'
alias log='git log'
alias logp='git log --date=iso --pretty=format:"%H %C(yellow)%ad %C(bold cyan)%ae %C(green)%s"'
alias pull='git pull'
alias push='git push'
alias branch='git branch'
alias branches='git log --oneline --decorate --graph --all'

